#!/bin/bash
# setup_native_deps_ios.sh — OpenDicomViewer
#
# Cross-compiles DCMTK 3.6.8 + OpenJPEG 2.5.0 as static libraries for iOS
# device (arm64) and iOS Simulator (arm64 only -- see NOTE below), then
# packages each library as an XCFramework under libs/xcframeworks/.
#
# NOTE (iOS port): the iOS Simulator x86_64 slice has been dropped. DCMTK's
# INSPECT_FUNDAMENTAL_ARITHMETIC_TYPES configure check needs to actually RUN
# a compiled probe binary to measure real sizeof/alignment/signedness values
# for the target CPU -- something that can't be determined by cross-compiling
# alone, and something char signedness genuinely differs on between arm64 and
# x86_64 (real behavioral risk, not just a build nuisance, in a DICOM viewer
# where pixel-data correctness matters). Since the build host here is Apple
# Silicon (arm64), this script reuses the arith.h already generated by a
# successful `scripts/setup_native_deps.sh` (macOS) run -- valid for both
# ios-arm64 (device) and the arm64 iOS Simulator slice, since they share the
# same CPU architecture/compiler/data model. There's no native x86_64 Mac
# here to generate a correct reference arith.h for that slice, and Apple
# Silicon Macs run the arm64 Simulator natively anyway (x86_64 Simulator is
# legacy, mainly for Intel Mac developers) -- so it's dropped rather than
# risking a silently-wrong build. Add it back later (from an Intel Mac or CI)
# if x86_64 Simulator support is ever actually needed.
#
# STATUS: cross-compiling DCMTK for iOS required several source-level and
# CMake-cache-level workarounds beyond what scripts/setup_native_deps.sh (the
# known-good macOS script this is based on) needs -- see the NOTEs throughout
# this file for what each one fixes and why.
#
# Usage:
#   ./scripts/setup_native_deps.sh       (macOS -- run this FIRST, see NOTE above)
#   ./scripts/setup_native_deps_ios.sh
#
# Output:
#   libs/xcframeworks/<library>.xcframework   (one per DCMTK/OpenJPEG library)
#   Each XCFramework has two slices: ios-arm64 (device) and
#   ios-arm64-simulator (Simulator, arm64 only).
#
# Licensed under the MIT License. See LICENSE for details.
set -e

PROJECT_ROOT="$(pwd)"
LIBS_DIR="$PROJECT_ROOT/libs"
XCFRAMEWORKS_DIR="$LIBS_DIR/xcframeworks"
TEMP_DIR="$PROJECT_ROOT/temp_build_ios"
CMAKE_DIR="$PROJECT_ROOT/temp_build/cmake"   # reuse the mac script's local CMake if present
MACOS_DCMTK_ARITH_H="$PROJECT_ROOT/temp_build/dcmtk-3.6.8/build/config/include/dcmtk/config/arith.h"
IOS_DEPLOYMENT_TARGET="17.0"

mkdir -p "$LIBS_DIR" "$XCFRAMEWORKS_DIR" "$TEMP_DIR"

# ---------------------------------------------------------------------------
# 0. CMake + the ios-cmake toolchain file
# ---------------------------------------------------------------------------
# Cross-compiling for iOS from a CMake project is notoriously easy to get
# subtly wrong: CMake's try_run() (used by DCMTK's and OpenJPEG's configure
# checks for endianness, type sizes, etc.) can't execute an iOS binary on the
# macOS build host, so a naive `-DCMAKE_SYSTEM_NAME=iOS` setup will hang or
# fail at configure time. Rather than hand-roll that logic (which I can't
# verify without a real toolchain), this script uses the community-maintained
# ios-cmake toolchain file (https://github.com/leetal/ios-cmake, MIT
# licensed), which specifically solves this. It's downloaded once and cached.
if [ ! -f "$CMAKE_DIR/CMake.app/Contents/bin/cmake" ]; then
    echo "Local CMake not found -- run scripts/setup_native_deps.sh first (it downloads" \
         "a local CMake this script reuses), or install CMake and adjust CMAKE_BIN below."
    mkdir -p "$CMAKE_DIR"
    cd "$TEMP_DIR"
    curl -L -O https://github.com/Kitware/CMake/releases/download/v3.29.0/cmake-3.29.0-macos-universal.tar.gz
    tar xzf cmake-3.29.0-macos-universal.tar.gz
    mv cmake-3.29.0-macos-universal "$CMAKE_DIR"
    rm cmake-3.29.0-macos-universal.tar.gz
fi
CMAKE_BIN="$CMAKE_DIR/CMake.app/Contents/bin/cmake"
echo "Using CMake at: $CMAKE_BIN"

IOS_TOOLCHAIN="$TEMP_DIR/ios.toolchain.cmake"
if [ ! -f "$IOS_TOOLCHAIN" ]; then
    echo "Downloading ios-cmake toolchain file (pinned to 4.5.0)..."
    curl -L -o "$IOS_TOOLCHAIN" \
        https://raw.githubusercontent.com/leetal/ios-cmake/4.5.0/ios.toolchain.cmake
fi

# ---------------------------------------------------------------------------
# 1. Fetch sources (shared across all platform slices)
# ---------------------------------------------------------------------------
if [ ! -d "$TEMP_DIR/openjpeg-2.5.0" ]; then
    echo "Downloading OpenJPEG 2.5.0..."
    cd "$TEMP_DIR"
    curl -L -o openjpeg-2.5.0.tar.gz https://github.com/uclouvain/openjpeg/archive/v2.5.0.tar.gz
    tar xzf openjpeg-2.5.0.tar.gz
fi

if [ ! -d "$TEMP_DIR/dcmtk-3.6.8" ]; then
    echo "Downloading DCMTK 3.6.8..."
    cd "$TEMP_DIR"
    curl -L -O https://dicom.offis.de/download/dcmtk/dcmtk368/dcmtk-3.6.8.tar.gz
    tar xzf dcmtk-3.6.8.tar.gz
    rm dcmtk-3.6.8.tar.gz
fi

if [ ! -f "$MACOS_DCMTK_ARITH_H" ]; then
    echo "ERROR: $MACOS_DCMTK_ARITH_H not found."
    echo "Run ./scripts/setup_native_deps.sh (the macOS build) successfully at least" \
         "once first -- this iOS script reuses the arith.h it generates (see the NOTE" \
         "at the top of this file for why)."
    exit 1
fi

# ---------------------------------------------------------------------------
# 1b. Patch DCMTK's own Darwin/iOS feature-test-macro flags
# ---------------------------------------------------------------------------
# Root-caused by diffing DCMTK's CMake/dcmtkPrepare.cmake against the actual
# failing clang invocation from a real build attempt: DCMTK 3.6.8 hand-builds
# CMAKE_CXX_FLAGS/CMAKE_C_FLAGS itself, per-Darwin-variant, in several
# separate branches of dcmtkPrepare.cmake. Its "plain macOS" branch (~line
# 498) adds -D_DARWIN_C_SOURCE, which is what makes fseeko/ftello visible to
# libc++'s <fstream> (used transitively by config/tests/arith.cc via
# ofstd/include/dcmtk/ofstd/ofstream.h). The branch(es) that fire for this
# iOS cross-compile (~lines 502 and 513, identified by matching the exact
# flag list -D_XOPEN_SOURCE_EXTENDED -D_XOPEN_SOURCE=500 ... -D_POSIX_C_SOURCE
# =199506L against a real failing build's clang command line) omit it -- an
# inconsistency in DCMTK's own platform detection, not something fixable by
# passing -DCMAKE_CXX_FLAGS=... on the `cmake` command line (tried first;
# confirmed by build output that DCMTK's own hand-built string always wins
# and any externally-supplied value never reaches the actual compile).
# Patching the source directly, once, right after download, is the reliable
# fix -- idempotent (checked via grep) so re-running this script is safe.
DCMTK_PREPARE_CMAKE="$TEMP_DIR/dcmtk-3.6.8/CMake/dcmtkPrepare.cmake"
if [ -f "$DCMTK_PREPARE_CMAKE" ] && ! grep -q '_POSIX_C_SOURCE=199506L -D_DARWIN_C_SOURCE' "$DCMTK_PREPARE_CMAKE"; then
    echo "Patching DCMTK's dcmtkPrepare.cmake to add -D_DARWIN_C_SOURCE to its iOS/Darwin flag branches..."
    sed -i '' \
        -e 's/-D_BSD_COMPAT -D_OSF_SOURCE -D_POSIX_C_SOURCE=199506L")/-D_BSD_COMPAT -D_OSF_SOURCE -D_POSIX_C_SOURCE=199506L -D_DARWIN_C_SOURCE")/' \
        "$DCMTK_PREPARE_CMAKE"
    if grep -q '_POSIX_C_SOURCE=199506L -D_DARWIN_C_SOURCE' "$DCMTK_PREPARE_CMAKE"; then
        echo "  Patch applied successfully."
    else
        echo "  WARNING: patch did not apply as expected -- inspect $DCMTK_PREPARE_CMAKE" \
             "manually around lines 495-515 (search for _POSIX_C_SOURCE=199506L) and compare" \
             "against the macOS branch a few lines above it, which already includes" \
             "-D_DARWIN_C_SOURCE and can be used as a template."
    fi
else
    echo "DCMTK dcmtkPrepare.cmake already patched (or not found yet) -- skipping."
fi

# ---------------------------------------------------------------------------
# 2. Build one platform slice (OpenJPEG, then DCMTK against it)
#    $1 = slice name (e.g. "ios-arm64"), $2 = ios-cmake PLATFORM value
# ---------------------------------------------------------------------------
build_slice() {
    local SLICE_NAME="$1"
    local IOS_CMAKE_PLATFORM="$2"
    local SLICE_DIR="$TEMP_DIR/slices/$SLICE_NAME"
    local OPENJPEG_INSTALL="$SLICE_DIR/openjpeg"
    local DCMTK_INSTALL="$SLICE_DIR/dcmtk"

    echo ""
    echo "=== Building slice: $SLICE_NAME (PLATFORM=$IOS_CMAKE_PLATFORM) ==="
    mkdir -p "$SLICE_DIR"

    echo "--- OpenJPEG ($SLICE_NAME) ---"
    rm -rf "$TEMP_DIR/openjpeg-2.5.0/build-$SLICE_NAME"
    mkdir -p "$TEMP_DIR/openjpeg-2.5.0/build-$SLICE_NAME"
    cd "$TEMP_DIR/openjpeg-2.5.0/build-$SLICE_NAME"
    "$CMAKE_BIN" .. \
        -DCMAKE_TOOLCHAIN_FILE="$IOS_TOOLCHAIN" \
        -DPLATFORM="$IOS_CMAKE_PLATFORM" \
        -DDEPLOYMENT_TARGET="$IOS_DEPLOYMENT_TARGET" \
        -DCMAKE_INSTALL_PREFIX="$OPENJPEG_INSTALL" \
        -DBUILD_SHARED_LIBS=OFF \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_CODEC=OFF \
        -DCMAKE_DISABLE_FIND_PACKAGE_TIFF=ON \
        -DCMAKE_DISABLE_FIND_PACKAGE_PNG=ON \
        -DCMAKE_DISABLE_FIND_PACKAGE_LCMS2=ON
    "$CMAKE_BIN" --build . --target install --parallel 4

    echo "--- DCMTK ($SLICE_NAME) ---"
    rm -rf "$TEMP_DIR/dcmtk-3.6.8/build-$SLICE_NAME"
    mkdir -p "$TEMP_DIR/dcmtk-3.6.8/build-$SLICE_NAME"

    # NOTE (iOS port): pre-seed arith.h reused from the macOS arm64 build (see
    # the NOTE at the top of this file). INSPECT_FUNDAMENTAL_ARITHMETIC_TYPES
    # (CMake/GenerateDCMTKConfigure.cmake) skips its whole try-compile-and-RUN
    # probe entirely as long as config/include/dcmtk/config/arith.h already
    # exists and is newer than config/tests/arith.cc -- placing a fresh copy
    # here (before cmake configure runs) satisfies that unconditionally, since
    # `cp` sets the destination's mtime to now. Only valid for arm64 slices
    # (device and arm64 Simulator) -- see the top-of-file NOTE for why x86_64
    # Simulator is skipped rather than getting a copy of this same file.
    mkdir -p "$TEMP_DIR/dcmtk-3.6.8/build-$SLICE_NAME/config/include/dcmtk/config"
    cp "$MACOS_DCMTK_ARITH_H" \
        "$TEMP_DIR/dcmtk-3.6.8/build-$SLICE_NAME/config/include/dcmtk/config/arith.h"

    cd "$TEMP_DIR/dcmtk-3.6.8/build-$SLICE_NAME"
    # NOTE (iOS port): DCMTK's CMake configure step originally failed at
    # INSPECT_FUNDAMENTAL_ARITHMETIC_TYPES (CMakeLists.txt:52), which
    # try-compiles config/tests/arith.cc -> ofstd/include/dcmtk/ofstd/ofstream.h
    # -> libc++'s <fstream>, which calls ::fseeko/::ftello unconditionally --
    # not visible under the feature-test macros DCMTK's iOS/Darwin branch of
    # CMake/dcmtkPrepare.cmake constructs for this platform. Passing
    # -DCMAKE_CXX_FLAGS/-DCMAKE_C_FLAGS here on the `cmake` command line was
    # tried first and confirmed NOT to work: dcmtkPrepare.cmake hand-builds
    # its own CMAKE_CXX_FLAGS/CMAKE_C_FLAGS string per Darwin variant and that
    # always wins by the time any actual compile happens. The real fix is the
    # source patch applied above (step 1b), which adds -D_DARWIN_C_SOURCE
    # directly to DCMTK's own flag-construction lines in dcmtkPrepare.cmake --
    # mirroring what DCMTK's own "plain macOS" branch already does. No flags
    # need to be (or should be) passed in from here anymore.
    # NOTE (iOS port): DCMTK's CMake config runs ~30 small DCMTK_TRY_COMPILE()
    # feature probes (CMake/dcmtkTryCompile.cmake) to detect compiler quirks.
    # That macro itself is fully graceful -- guarded by `if(NOT DEFINED
    # "${VAR}")` and never raises an error on its own; a failed probe just
    # logs "-- no" and moves on. Several probes (e.g. PASSWD_GECOS_IS_DEFINE_
    # TO_PASSWD, HAVE_DECLSPEC_ALIGN/DEPRECATED/DEPRECATED_MSG) are *designed*
    # to fail-to-compile as their normal answer on this platform (MS-only
    # __declspec attributes without -fms-extensions; pw_gecos genuinely not
    # being a macro alias, confirmed via the compiler's own "note:
    # 'passwd::pw_gecos' declared here" pointing at a real struct field) --
    # yet those failures were showing up bundled into a hard configure-time
    # FATAL_ERROR still attributed to INSPECT_FUNDAMENTAL_ARITHMETIC_TYPES
    # (CMakeLists.txt:52) further down. The exact mechanism connecting the
    # two wasn't fully pinned down, but since DCMTK_TRY_COMPILE's guard means
    # pre-seeding the cache variable skips the probe outright regardless of
    # mechanism, that's the fix: find the guard var in
    # CMake/GenerateDCMTKConfigure.cmake, confirm the objectively correct
    # answer for arm64/iOS from the compiler's own error output, pre-seed it
    # below. Add more `-D<VAR>=<value>` lines here as further probes surface.
    #   - HAVE__FINDFIRST=0: a DIFFERENT category of false positive -- this
    #     one comes from CMake's own stock CHECK_FUNCTION_EXISTS(_findfirst
    #     HAVE__FINDFIRST) module macro (GenerateDCMTKConfigure.cmake:608,
    #     one of ~50 unconditional function-existence probes), which is
    #     link-based rather than compile-based. _findfirst is a Windows CRT
    #     function that categorically doesn't exist on iOS/Darwin, yet the
    #     link-only check reports it as found when cross-compiling for iOS --
    #     a known category of gotcha for link-based existence checks on
    #     Apple's linker when cross-compiling. When HAVE__FINDFIRST is
    #     wrongly true, ofstd/libsrc/offilsys.cc picks its Windows
    #     directory-iterator implementation (::_finddata_t/_findclose/
    #     _findnext) over the POSIX opendir/readdir one, which then fails to
    #     compile since those symbols aren't declared in iOS's headers
    #     either. Only this one symbol has been confirmed problematic so far
    #     (scanned the rest of the ~50-probe list for other obviously
    #     Windows-only names and found none) -- if another one of those
    #     probes turns out to also be a false positive, it'll surface as a
    #     build error the same way this one did, and gets fixed the same way.
    #   - HAVE_LIBRT=0: same false-positive category, this time from
    #     CHECK_LIBRARY_EXISTS(rt mq_open "" HAVE_LIBRT) in
    #     CMake/dcmtkPrepare.cmake (~line 671), which feeds into THREAD_LIBS
    #     (linked into oficonv and its mkcsmapper/mkesdb build-time tools).
    #     There is no librt on any Apple platform at all (its functionality
    #     is just part of libSystem) -- the link-only check reports it found
    #     anyway when cross-compiling for iOS, causing "ld: library 'rt' not
    #     found" at actual link time.
    #   - HAVE_LIBNSL_MAIN/HAVE_LIBNSL=0, HAVE_LIBSOCKET_MAIN/HAVE_LIBSOCKET=0:
    #     same false-positive category again, from DCMTK_TEST_SOCKET_LIBRARY
    #     (dcmtkPrepare.cmake ~line 755), which runs two CHECK_LIBRARY_EXISTS
    #     link probes per library name (a "does `main` link" sanity probe,
    #     then the real symbol probe) and appends to SOCKET_LIBS if either
    #     comes back positive -- both must be pre-seeded since the macro only
    #     skips the second probe if the first is already truthy. Called for
    #     nsl (confirmed false positive: "ld: library 'nsl' not found") and,
    #     immediately after in the same file, for socket -- Darwin has no
    #     separate libnsl or libsocket at all (both are legacy SysV/Solaris
    #     libraries; their functionality is just part of libSystem/libc on
    #     Apple platforms), so socket is pre-seeded here too even though it
    #     hasn't actually failed yet, on the same reasoning as the others.
    #   - BUILD_APPS=OFF (CMake/dcmtkPrepare.cmake:156, "Build command line
    #     applications and test programs."): none of DCMTK's command-line
    #     apps (dcmdump, dcm2pdf, pdf2dcm, xml2dcm, ...) or test programs
    #     (oficonv_tests, ofstd_tests, ...) are needed here -- Package.swift's
    #     DCMTKWrapper target only links the underlying libraries (dcmdata,
    #     dcmimage, ofstd, etc.). Turning this off skips building them
    #     entirely, which is both unnecessary work AND, as of dcm2pdf.cc
    #     calling system() (unavailable on iOS -- a real Apple sandboxing
    #     restriction, not a bug to patch around), a real source of iOS
    #     build failures unrelated to anything the Swift package needs.
    "$CMAKE_BIN" .. \
        -DCMAKE_TOOLCHAIN_FILE="$IOS_TOOLCHAIN" \
        -DPLATFORM="$IOS_CMAKE_PLATFORM" \
        -DDEPLOYMENT_TARGET="$IOS_DEPLOYMENT_TARGET" \
        -DCMAKE_INSTALL_PREFIX="$DCMTK_INSTALL" \
        -DBUILD_SHARED_LIBS=OFF \
        -DCMAKE_BUILD_TYPE=Release \
        -DPASSWD_GECOS_IS_DEFINE_TO_PASSWD=0 \
        -DHAVE_DECLSPEC_ALIGN=0 \
        -DHAVE_DECLSPEC_DEPRECATED=0 \
        -DHAVE_DECLSPEC_DEPRECATED_MSG=0 \
        -DHAVE__FINDFIRST=0 \
        -DHAVE_LIBRT=0 \
        -DHAVE_LIBNSL_MAIN=0 \
        -DHAVE_LIBNSL=0 \
        -DHAVE_LIBSOCKET_MAIN=0 \
        -DHAVE_LIBSOCKET=0 \
        -DBUILD_APPS=OFF \
        -DDCMTK_WITH_TIFF=OFF \
        -DDCMTK_WITH_PNG=OFF \
        -DDCMTK_WITH_XML=OFF \
        -DDCMTK_WITH_OPENSSL=OFF \
        -DDCMTK_WITH_ICONV=OFF \
        -DDCMTK_ENABLE_CXX11=ON \
        -DDCMTK_WITH_OPENJPEG=ON \
        -DCMAKE_PREFIX_PATH="$OPENJPEG_INSTALL"
    "$CMAKE_BIN" --build . --target install --parallel 4

    echo "Slice $SLICE_NAME done -> $DCMTK_INSTALL, $OPENJPEG_INSTALL"
}

# Device: arm64 only (no iOS device ships any other architecture in the
# iOS 17+ deployment target range this project uses).
build_slice "ios-arm64" "OS64"

# Simulator: arm64 only -- see the top-of-file NOTE for why the x86_64
# Simulator slice (and the lipo step that used to combine it with this one
# into a "universal" simulator library) has been dropped.
build_slice "ios-arm64-simulator" "SIMULATORARM64"

# ---------------------------------------------------------------------------
# 3. Simulator library set (arm64 only -- see NOTE above; kept as its own
#    directory, named "-universal" for continuity with make_xcframework
#    below and in case an x86_64 slice is added back later)
# ---------------------------------------------------------------------------
echo ""
echo "=== Using arm64-only Simulator libraries (x86_64 dropped -- see NOTE at top of file) ==="
SIM_UNIVERSAL_DIR="$TEMP_DIR/slices/ios-simulator-universal"
mkdir -p "$SIM_UNIVERSAL_DIR/lib"
cp "$TEMP_DIR/slices/ios-arm64-simulator/dcmtk/lib"/*.a "$SIM_UNIVERSAL_DIR/lib/" 2>/dev/null || true
cp "$TEMP_DIR/slices/ios-arm64-simulator/openjpeg/lib"/*.a "$SIM_UNIVERSAL_DIR/lib/" 2>/dev/null || true

# Headers are architecture-independent -- just reuse the arm64 simulator ones.
cp -R "$TEMP_DIR/slices/ios-arm64-simulator/dcmtk/include" "$SIM_UNIVERSAL_DIR/include-dcmtk"
cp -R "$TEMP_DIR/slices/ios-arm64-simulator/openjpeg/include" "$SIM_UNIVERSAL_DIR/include-openjpeg"

# ---------------------------------------------------------------------------
# 4. Package each library as an XCFramework (device + universal simulator)
# ---------------------------------------------------------------------------
echo ""
echo "=== Creating XCFrameworks ==="
DEVICE_DCMTK_LIBDIR="$TEMP_DIR/slices/ios-arm64/dcmtk/lib"
DEVICE_DCMTK_INCLUDE="$TEMP_DIR/slices/ios-arm64/dcmtk/include"
DEVICE_OPENJPEG_LIBDIR="$TEMP_DIR/slices/ios-arm64/openjpeg/lib"
DEVICE_OPENJPEG_INCLUDE="$TEMP_DIR/slices/ios-arm64/openjpeg/include"

make_xcframework() {
    local LIB_NAME="$1"          # e.g. "dcmdata" (file will be libdcmdata.a)
    local DEVICE_LIBDIR="$2"
    local DEVICE_INCLUDE="$3"
    local SIM_LIBDIR="$4"
    local SIM_INCLUDE="$5"

    local FILE_NAME="lib${LIB_NAME}.a"
    local DEVICE_LIB="$DEVICE_LIBDIR/$FILE_NAME"
    local SIM_LIB="$SIM_LIBDIR/$FILE_NAME"
    local OUT="$XCFRAMEWORKS_DIR/${LIB_NAME}.xcframework"

    if [ ! -f "$DEVICE_LIB" ] || [ ! -f "$SIM_LIB" ]; then
        echo "  SKIP $LIB_NAME (missing device or simulator .a -- check build logs above)"
        return
    fi

    rm -rf "$OUT"
    xcodebuild -create-xcframework \
        -library "$DEVICE_LIB" -headers "$DEVICE_INCLUDE" \
        -library "$SIM_LIB" -headers "$SIM_INCLUDE" \
        -output "$OUT"
    echo "  created $OUT"
}

# DCMTK libraries actually linked by Package.swift's DCMTKWrapper target today.
DCMTK_LIBS="dcmimage dcmimgle dcmdata oflog ofstd dcmjpeg dcmjpls dcmtkcharls ijg8 ijg12 ijg16 oficonv"
for lib in $DCMTK_LIBS; do
    make_xcframework "$lib" "$DEVICE_DCMTK_LIBDIR" "$DEVICE_DCMTK_INCLUDE" \
        "$SIM_UNIVERSAL_DIR/lib" "$SIM_UNIVERSAL_DIR/include-dcmtk"
done
# dcmnet/dcmqrdb/dcmtls (currently built but unused -- see PACS networking task)
for lib in dcmnet dcmqrdb dcmtls; do
    make_xcframework "$lib" "$DEVICE_DCMTK_LIBDIR" "$DEVICE_DCMTK_INCLUDE" \
        "$SIM_UNIVERSAL_DIR/lib" "$SIM_UNIVERSAL_DIR/include-dcmtk"
done

make_xcframework "openjp2" "$DEVICE_OPENJPEG_LIBDIR" "$DEVICE_OPENJPEG_INCLUDE" \
    "$SIM_UNIVERSAL_DIR/lib" "$SIM_UNIVERSAL_DIR/include-openjpeg"

echo ""
echo "Done. XCFrameworks are in: $XCFRAMEWORKS_DIR"
echo "Package.swift's DCMTKWrapper target still needs to be switched from its"
echo "current unsafeFlags-based -L linking to .binaryTarget entries pointing"
echo "at these XCFrameworks for the iOS platform slice -- see docs/iOS-Build.md."
